name: Deploy Docs to Github pages
on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'src/apps/docs/**'
      - 'src/packages/**'
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all packages
        run: pnpm run build:packages

      - name: Build docs
        working-directory: ./src/apps/docs
        run: pnpm run build

      - name: Deploy docs
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_brach: gh-pages
          build_dir: src/apps/docs/storybook-static
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
