name: Pre-release package theme
on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - src/packages/theme/*
jobs:
  release:
    name: Pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      # - name: Run tests
      # run: pnpm run test
      - name: Run build
        run: pnpm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
